# Generated by Django 3.0.5 on 2020-04-05 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField(max_length=10)),
                ('send_email', models.BooleanField(default=True)),
                ('send_sms', models.BooleanField(default=True)),
                ('purpose', models.CharField(max_length=30)),
                ('amount', models.IntegerField(verbose_name=range(9, 200001))),
            ],
        ),
    ]
