# Generated by Django 3.0.5 on 2020-04-05 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20200405_0115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
