# Generated by Django 3.0.5 on 2020-04-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_base_paymentdetail_razorpayresponsew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetail',
            name='PayType',
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='Description',
            field=models.CharField(default='Payment', max_length=100),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='mobile',
            field=models.PositiveIntegerField(default=9999999999, verbose_name=range(6000000000, 9999999999)),
        ),
    ]
