# Generated by Django 3.0.5 on 2020-04-16 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20200416_1034'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RazorpayResponsew',
            new_name='RazorpayResponse',
        ),
    ]
